title: "Sabbrumm"
description: >- # this means to ignore newlines until "baseurl:"
  Note: C-NOVA is not a trademark but i will be very sad if you use it without asking me
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: sabbrumm
theme: minima
header_pages:
  - docs/README.md
plugins:
  - jekyll-feed
  - jekyll-mentions
disqus:
  shortname: placeholder # this is a placeholder to enable comments
