title: "Sabbrumm"
description: >- # this means to ignore newlines until "baseurl:"
  C-NOVA не торговая марка, но используя ее без моего ведома вы меня разочаровываете...
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: sabbrumm
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima: 
  social_links:
     - { platform: github,         user_url: "https://github.com/sabbrumm" }
     - { platform: telegram,       user_url: "https://t.me/sabbrumm" }
